# -*- coding: utf-8 -*-
"""question_7b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZeNsJwGjJuMOFxt0mvuNfzQZk0NC_rQ3
"""

import numpy as np 
import scipy as sp 
import scipy.special as sc 
curr = 1. 
e_val = 1. 
esmp=1.1102230246251565e-16 # I have taken it from question 6b
def error(curr,e_val,esmp):
  while True: 
    a = 1/sc.factorial(curr, exact=True) 
    e_val += a 
    if (a<=esmp): 
      break
    curr += 1
  reler = abs((np.e-e_val)/np.e)
  return reler 
r=error(curr,e_val,esmp)
print("\nThe relative error is %1.15f" % r)