# -*- coding: utf-8 -*-
"""Question_7a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kUNpm75mk0Hluv-LCKLvXB8yuouRbCDL
"""

import matplotlib.pyplot as p
def limit_e(n): 
  return (1+1/n)**n
reler=[] 
N = [10**m for m in range(1, 16)] 
for n in N: 
  y=limit_e(n) 
  t=abs((y-np.e)/np.e)
  reler.append(t)
p.figure() 
p.plot(N, reler, 'bo') 
p.xscale('log');p.yscale('log');p.grid(True) 
p.ylabel("$|\\frac{e - (1 + 1/n)^n}{e}|$");p.xlabel("$n$")